#+SETUPFILE: ./setup/maindishrecipes.setup
#+TITLE: Main Dish Recipes (HOMEPAGE LINK: https://www.musimatic.xyz)
#+OPTIONS: num:nil
* README For "Main Dish Recipes":
NOTE: These are recipes that I have gathered from the internet, and are mostly NOT my own.

I will indicate my own recipes with a "By: Samuel Banya" section in its title whenever
necessary.

This being noted, I have the related links whenever possible to the original creators, so
feel free to visit those links to find out even more great food recipes.

I am including them here in one quick and accessible page for myself, but also for you to
enjoy in plain-text format to be read on any device, courtesy of Emacs Org Mode :)
* Burma Superstar Style Tea Leaf Salad Recipe
** Link:
- https://www.mercurynews.com/2017/04/15/recipe-burma-superstars-tea-leaf-salad/
** Ingredients For Tea Leaf Dressing:
- 1/2 cup packed cup (about 2 ounces) whole fermented tea leaves (laphet) or 1/3 cup packed seasoned tea leaf paste (without oil)
- 1/3 cup canola oil
- 1 garlic clove, coarsely chopped
- 1/4 teaspoon dried chile flakes
- 1 teaspoon lime or lemon juice
- Salt
** Directions For Tea Leaf Dressing:
1. If using whole, unseasoned laphet leaves, soak them for 5 minutes in cold water to extract some of the bitterness.

2. Drain, squeezing the leaves to remove excess water.

3. Taste the leaves. If they still taste extremely bitter, soak and drain again.

4. Skip this step if using a seasoned paste.

5. Put the leaves or paste in a food processor with the garlic and chile flakes; pulse a few times.

6. Add the lemon juice and half the oil, briefly pulse.

7. Then, with the processor running, drizzle in the rest of the oil.

8. If the leaves are not preseasoned, add 1 teaspoon salt.

9. If the leaves are already seasoned, add only a pinch or two of salt.
** Ingredients For Fried Garlic Chips and Garlic Oil:
- 1/2 cup canola oil
- 1/3 cup thinly sliced fresh garlic
** Directions For Fried Garlic Chips And Garlic Oil:
1. Line a heatproof bowl with a strainer.

2. Line a plate with paper towels.

3. In a wok or small saucepan, heat the oil over medium heat for a minute or two (the oil shouldn’t be scorching hot).

4. Add garlic and gently stir.

5. When bubbles start to form rapidly around the garlic, decrease heat to low and cook.

6. Stir often, until the garlic is an even golden color and nearly completely crisp, about 3 minutes.

7. If the garlic starts to darken too quickly, remove it from the heat and let it continue to fry in the oil.

8. Garlic and oil into the strainer.

9. Lift the strainer up and shake off the excess oil.

10. Scatter garlic onto the lined plate.

11. The garlic should crisp up as it cools.

12. The chips can be stored in an airtight container at room temperature for 1 month.

13. Refrigerate the oil up to 6 months.
** Ingredients For Fried Yellow Split Peas:
- 1/3 cup yellow split peas
- 1/2 cup canola oil
- Pinch of salt
** Directions For Fried Yellow Split Peas:
1. Place peas in a bowl and cover 1 inch of water.

2. Soak at least 4 hours or overnight.

3. Drain split peas through a fine-mesh strainer, shaking off the excess water.

4. Line a plate with paper towels.

5. In a wok or small saucepan, heat the oil over medium-high heat for 1 minute.

6. Add the split peas.

7. Once the oil starts to bubble rapidly around the split peas, lower the heat slightly and continue to fry.

8. Stir often, until they begin to crisp up and turn slightly darker, about 5 minutes.

9. Drain well.

10. Scatter the split peas on the lined plate and season with salt.

11. The split peas should be crunchy, but not rock-hard, once cooled.

12. Store in an airtight container at room temperature for up to 2 weeks.
** Ingredients For Tea Leaf Salad
- 6 cups thinly sliced romaine lettuce (about 1 1/2 heads romaine)
- 1/2 cup tea leaf dressing (see recipe)
- 1/4 cup fried garlic chips (see recipe)
- 1/4 cup fried yellow split peas (see recipe)
- 1/4 cup coarsely chopped toasted peanuts
- 1/4 cup toasted sunflower seeds
- 1 tablespoon toasted sesame seeds
- 1 Roma tomato, seeded and diced
- 1 small jalapeño, seeded and diced (about 1/4 cup)
- 1 tablespoon shrimp powder
- 2 teaspoons fish sauce or a few generous pinches salt
- 1 lemon or lime, cut into wedges
** Directions For Assembling The Tea Leaf Salad:
1. Place a bed of lettuce in the center of a large platter.

2. Spoon the tea leaf dressing into the center of the lettuce.

3. Around the lettuce, arrange separate piles of fried garlic, split peas, peanuts, sunflower seeds, sesame seeds, tomato and jalapeño.

4. Sprinkle with shrimp powder and drizzle with fish sauce.

5. Before serving, squeeze 2 lemon wedges over the plate.

6. Using 2 forks, mix the ingredients together until the tea leaves lightly coat the lettuce.

7. Taste, adding more lemon or fish sauce at the table, if desired.
* Cheeseburger Casserole Recipe
** Links:
- https://www.myrecipes.com/recipe/cheeseburger-casserole
- https://www.youtube.com/watch?v=_wZkmBUkdbE
** Ingredients:
- 6 thick-cut bacon slices, chopped
- 2 large yellow onions, thinly sliced
- 1 Tbsp. Worcestershire sauce
- 1 1/4 tsp. kosher salt, divided
- 1 tsp. black pepper, divided
- 1 1/2 lb. (90/10 lean) ground beef sirloin
- 1/4 cup ketchup
- 2 Tbsp. yellow mustard
- 8 (3/4-oz.) American cheese slices
- 3 brioche hamburger buns, cut in 3/4-in. cubes
- 4 oz. sharp Cheddar cheese, shredded (about 1 cup)
- Shredded lettuce, diced tomato, pickle slices, mayonnaise
** Directions:
1. Cook bacon in a large nonstick skillet over medium, stirring occasionally, until browned and crisp.

2. Transfer to a plate; set aside.

3. Pour off half of the bacon drippings from skillet, and reserve.

4. Add onions to skillet with remaining drippings over medium-low; cook, stirring occasionally, until browned and caramelized, about 30 minutes.

5. Stir in Worcestershire, 1/2 teaspoon of the salt, and 1/4 teaspoon of the pepper.

6. Transfer to a bowl; set aside.

7. Preheat oven to 350°F.

8. Heat skillet over medium-high.

9. Add ground beef, 1/2 teaspoon of the pepper, and remaining 3/4 teaspoon salt; cook, stirring occasionally, until browned, 8 to 10 mintues.

10. Stir in ketchup and mustard; remove from heat.

11. Spread beef mixture in bottom of a lightly greased 3-quart baking dish.

12. Top with caramelized onions and crumbled bacon.

13. Arrange cheese slices over bacon.

14. Toss bun cubes in reserved bacon drippings, and place in an even layer over cheese slices.

15. Sprinkle with cheddar cheese and remaining 1/4 teaspoon pepper.

16. Bake in preheated oven until golden and bubbly, about 20 minutes.

17. Serve with desired toppings.
* Chicken Fried Steak Recipe
** Link:
- https://www.foodnetwork.com/recipes/ree-drummond/chicken-fried-steak-with-gravy-recipe-1925056
** Ingredients (Chicken Fried Steak):
- 1 1/2 cups whole milk
- 2 large eggs
- 2 cups all-purpose flour
- 2 teaspoons seasoned salt
- Freshly ground black pepper
- 3/4 teaspoon paprika
- 1/4 teaspoon cayenne pepper
- 3 pounds cube steak (tenderized round steak that's been extra tenderized)
- Kosher salt
- 1/2 cup canola or vegetable oil
- 1 tablespoon butter
** Ingredients (Gravy):
- 1/3 cup all-purpose flour
- 3 to 4 cups whole milk
- 1/2 teaspoon seasoned salt
- Freshly ground black pepper
- Mashed potatoes, for serving
** Directions:
1. For the steak: Begin with setting up an assembly line of dishes.

2. Mix the milk with the eggs in one; the flour mixed with the seasoned salt, 1 1/2 teaspoons black pepper, paprika and cayenne in another; and the meat in a third.

3. Then have one clean plate at the end to receive the breaded meat.

4. Work with one piece of meat at a time.

5. Sprinkle both sides with kosher salt and black pepper, then place it in the flour mixture.

6. Turn to coat.

7. Place the meat into the milk/egg mixture, turning to coat.

8. Finally, place it back in the flour and turn to coat (dry mixture/wet mixture/dry mixture).

9. Place the breaded meat on the clean plate, then repeat with the remaining meat.

10. Heat the oil in a large skillet over medium heat.

11. Add the butter.

12. Drop in a few sprinkles of flour to make sure it's sufficiently hot.

13. When the butter sizzles immediately, you know it's ready. (It should not brown right away, if it does, the fire is too hot.)

14. Cook the meat, 3 pieces at a time, until the edges start to look golden brown, about 2 minutes each side.

15. Remove the meat to a paper towel-lined plate and keep them warm by covering lightly with another plate or a sheet of foil.

16. Repeat until all the meat is cooked.

17. After all the meat is fried, pour off the grease into a heatproof bowl.

18. Without cleaning the skillet, return it to the stove over medium-low heat.

19. Add 1/4 cup of the grease back to the skillet and allow it to heat up.

20. For the gravy: When the grease is hot, sprinkle the flour evenly over the grease.

21. Using a whisk, mix the flour with the grease, creating a golden-brown paste.

22. Add more flour if it looks overly greasy; add a little more grease if it becomes too pasty/clumpy.

23. Keep cooking until the roux reaches a deep golden brown color.

24. Pour in the milk, whisking constantly.

25. Add the seasoned salt and black pepper to taste and cook, whisking, until the gravy is smooth and thick, 5 to 10 minutes.

26. Be prepared to add more milk if it becomes overly thick.

27. Be sure to taste to make sure gravy is sufficiently seasoned.

28. Serve the meat next to a big side of mashed potatoes.

29. Pour gravy over the whole shebang!

* Deep Dish Pizza Recipe
** Link:
- The 4 keys to make perfect CHICAGO DEEP DISH pizza every time (https://www.youtube.com/watch?v=89RYM6k0tKA)
** Dough Ingredients:
- 450g or about 3 1/4 cup flour
- 40g or 1/4 cup cornmeal
- 12g or 3 tsp sugar  15g or 3 tsp salt
- 275g or 1 1/4 cup water (85F)
- 110g or 8 tbsp (1 stick) butter cubed
- 9g or 3 tsp yeast
** Sauce Ingredients:
- 1 28oz can nice crushed tomato
- 1/4 red onion (grated)
- 2 garlic cloves ( run through press or minced)
- 40g or 2 tbps tomato paste
- 10g or 1 tbps sugar
- 1g or 1/2 tsp dried basil
- 1g or 1/2 tsp dried oregano
- 2-3 tbps butter
- 5g salt or 1 tsp
** Sausage Ingredients:
- 1 lb fatty ground pork
- 7g or 1.5 tsp salt
- 5g or 1 tsp sugar
- 3g or 1 tsp paprika
- 1g or 1/2 tsp dried sage
- 1g or 1/2 tsp black pepper
- 5g or 1.5 tsp red wine vinegar
- 1g or 1/2 tsp chile flake
- 1g or 1/2 tsp garlic powder
- 2g or 1 tsp toasted crushed fennel seed
** Directions To Prepare Sauce:
1. In a medium saute or sauce pan, preheat over medium heat, melt butter.

2. Add in onion and garlic and 5g salt, then sweat until translucent and starting to take on color.

3. Add in tomato paste and fry until rusty color emerges (30-40 seconds).

4. Add in crushed tomatoes, sugar, dried herbs and cook on low heat for 20 minutes stir often, cool for later pizza building.
** Directions To Prepare Sausage:
1. Fold ingredients to combine, cook a little off to taste for seasoning.
** Directions To Prepare Entire Pizza:
1. Combine dry ingredients in food processor, add in cubed butter and run food processor until incorporated and pebble-like.

2. While running, stream in warm water until combines, run for 30-40 seconds total.

3. Transfer to bowl and let rise for 90 minutes.

4. Divide into 2 equal pieces and shape into loose rounds, move to oiled sheet tray and cover with another sheet tray.

5. Let rise 1 hour.

6. Then roll into 12" round, oil a 9"-10 cast iron (LINK BELOW) or cake pan with 3 TBPS olive oil.

7. Lay in rolled out dough and then build pizza: CHEESE + SAUSAGE + SAUCE + PARM CHILE FLAKE .

6. Bake 30-40 minutes in 425 oven until crust is fried and golden.

7. Let cool 10 minutes then serve.

* Gluten Free Bread Recipe
** Link:
- https://www.goodforyouglutenfree.com/gluten-free-sandwich-bread/
** Ingredients:
- 3 cups Bob’s Red Mill 1-to-1 Gluten-Free Flour blend 430 grams
- 2 Tbsp light brown sugar
- 2 tsp instant yeast equivalent to one packet
- 2 tsp Kosher salt
- 1 cup warm milk or milk substitute
- 1 Tbsp raw honey
- 4 Tbsp soft butter or butter substitute
- 3 large eggs
** Directions:
1. Combine flour, brown sugar, yeast, salt in the bowl of your standing mixer.

2. Attach the paddle attachment to your standing mixer and slowly mix all ingredients on low speed.

3. Drizzle in milk, then add honey and butter and continue to mix well.

4. Turn mixer to medium speed and add each egg, one at a time until incorporated.

5. Once all the eggs are added, mix dough for 1 minute until all ingredients are well combined.

6. The batter will be sticky and soft (not like normal bread dough).

7. Grease an 8.5 x 4.5" loaf pan and gently pour dough into the pan without deflating it.

8. Cover with plastic wrap and place in warm spot to rise for 90-120 minutes.

9. Preheat oven to 350º F and bake for 38-40 minutes until the top is slightly browned and the dough is cooked through.

10. Place bread on a wire rack to cool completely.

11. Use a serrated bread knife to cut bread into slices.

12. The bread tastes fantastic toasted and lasts for several days when wrapped in plastic wrap.
* Gnocchi Recipe From Gennaro Contaldo
** Links:
*** Recipe Link:
- https://www.yellowmellowlife.com/gennaro-contaldos-gnocchi/

*** YouTube Video Links:
- Simple Gnocchi Recipe (Video in which Genarro goes over how to make Gnocci in an easier all-in-one video):
+ https://www.youtube.com/watch?v=FveqjpehElM

Jamie Oliver's YouTube Videos Featuring Gennaro Making Gnocchi:
- Gennaro makes Gnocchi (Part 1):
+ https://www.youtube.com/watch?v=LRmPcaGAG0s&t=18s

- Amazing Gnocchi Al Forno with Gennaro Contaldo Video (Part 2):
+ https://www.youtube.com/watch?v=GqxE5hBe7LA&t=49s
** Ingredients:
*** Gnocci Ingredients:
- 2 pounds potatoes (roughly 1 kg)
- 2 egg yolks
- 1 cup all-purpose flour
- Leaves from few sprigs of coriander – chopped
- Salt and pepper to taste
- Rice flour to dust (all-purpose flour can also be used)
*** Sage Butter Sauce Ingredients:
- Quarterstick of butter
- Handful of sage
- 1/2 cup / 100 grams Fontina cheese
- Parmesean cheese to grate ontop of finished Gnocchi
** Directions:
1. The first thing is to boil potatoes. It helps if your potatoes are roughly of the same size. That way they all take the same time to cook.

2. Otherwise, potatoes can also be baked.

3. The only thing to keep in mind is that we want the potatoes to get cooked, but not overcook.

4. If you are boiling them, make sure you take them out well on time or else I have noticed water seeping into potatoes making them a little soggy.

5. Boil or bake, what we are looking for is a cooked potato, whose skin you can peel easily with hand.

6. And when you cut it in two pieces, it should feel fluffy.

7. The method that Gennaro recommends (and which I use) is putting raw potatoes in a pot full of cold water.

8. Then, I let the water come to a boil.

9. After that boil them for additional 20 minutes.

10. If not, keep going for another 10 minutes.

11. I use the toothpick check to check my potatoes: Insert the toothpick in the potatoes – if it goes in and comes out easily, they are done.

12. After the potatoes are boiled, peeled them at your own convenience. However, let them come at room temperature before you go to the next step.

13. Now we need to mash the potatoes You can crumble them using your hands. Many people use potato ricer, you can even use a fork. I use a grater.

14. Make sure that the grated/ mashed potato remains flaky and retains its shape. Try not to handle it too much.

15. Now sprinkle a nice amount of rice flour on your work surface.

16. Put your grated potatoes in the shape of a well. Add in chopped coriander leaves and salt and pepper to taste.

17. Now dust the all purpose flour on your well. Inside the well, dump the 2 egg yolks.

18. Now start kneading. Remember not to apply a lot of pressure to your dough. Instead work with light hands and just try to bring everything together.

19. Feel free to add in a little more all purpose flour if you require. But just don’t go overboard with it.

20. The secret of good gnocchi, according to me, is to have as much as possible of potato and as little as possible of flour. Lot of potato, perfect!

21. Your gnocchi would be soft and light. Lot of flour, not perfect…gnocchi would be thick and heavy.

22. You’ll be left with nice ball of dough in no time.

23. Now take a little portion out of the dough and roll it into a rope, with thickness that of a cigar.

24. Dust the tip of a knife with flour and start cutting in pieces about 1 inch wide. You got your gnocchi.

25. You can get more creative and give each of gnocchi pieces a nice shape. The classic being indentation by a fork.

26. One other famous shape is the pillow shape. Just give a little dig in the middle of your gnocchi.

27. You can make balls or ovals, possibilities are endless. n

28. Keep placing them on a dusted surface.

29. Now if you are making the gnocchi right at this moment, just bring a large pot of water to boil.

30. Add in a little salt and your gnocchi to it. It is a good idea to tilt the pot side to side every once in a while to stop gnocchi from sticking.

31. Let gnocchi simmer in water till it starts floating at the top of the water.

32. At this point, take your gnocchi out using a ladle.

33. Leave it to steam dry for another 2 minutes before using it.

34. Make the sage butter sauce by using a quarterstick of butter in a saute pan, add a handful of sage. then add 1/2 cup of fontina cheese.

35. Add the boiled gnocchi into the pan, and grate parmesean cheese on top.

36. Put the oven's broiler mode on, and then add the pan into the top broiler of the oven for 1 minute or so until the cheese crisps a bit.

37. If you are intending to use your gnocchi later, dust your uncooked gnocchi with a generous amount of flour.

38. Spread it on a plate and keep it in deep freezer till it becomes as hard as stones.

39. After that, just store it in a zip lock and tuck it away in your deep freezer till next time.
* Goulash Recipe
** Link:
- https://www.spendwithpennies.com/hungarian-goulash/
** Ingredients:
- 2 medium onions
- 2 teaspoons butter or lard (preferred)
- 1 teaspoon caraway seeds
- 2 tablespoons paprika
- 1/4 cup flour
- 1 1/2 pound stewing beef trimmed and cut into 1 inch cubes
- 2 cups beef broth or water
- 1 cup diced tomatoes canned
- 1 teaspoon salt
- 1/4 teaspoon pepper
** Optional Ingredients:
- 1 1/2 cup carrots optional
- 3 cups potatoes optional
** Directions:
1. In a large pot, melt butter and add onion.

2. Cook till translucent.

3. Stir in caraway seeds and paprika and mix well.

4. In a bowl, dredge the stew beef with flour.

5. Add beef to the onion mixture and cook for about 2-3 minutes.

6. Slowly add about 1/4 cup of the beef broth to lift the brown bits off the bottom of the pan.

7. Then add remaining broth, diced tomatoes (potatoes and carrots if using), salt and pepper.

8. Stir and bring to a boil, cover, then reduce to a simmer for about 1 1/2 - 2 hours or until tender.
* Hawaiian Chicken Casserole Recipe
** Links:
- https://www.myrecipes.com/recipe/hawaiian-chicken-casserole
- https://www.youtube.com/watch?v=_wZkmBUkdbE
** Ingredients:
- 1 Tbsp. canola oil
- 1 Tbsp. minced fresh ginger
- 1 Tbsp. minced garlic
- 1 jalapeño chile, seeded and chopped
- 3/4 cup sweet onion, diced
- 3/4 tsp. kosher salt
- 2/3 cup light brown sugar
- 1/3 cup soy sauce
- 3 Tbsp. ketchup
- 2 Tbsp. rice vinegar
- 1 1/2 cups diced fresh pineapple
- 1 1/2 cups diced red bell pepper
- 1 1/2 lb. frozen, fully-cooked crispy breaded chicken strips, thawed and cut in 1 1/2-in. pieces
- 1/2 cup sliced fresh scallions
- 3 cups cooked jasmine rice
** Directions:
1. Preheat oven to 375°F.

2. Heat oil in a medium saucepan over medium-high.

3. Add ginger, garlic, and jalapeño; cook, stirring often, until fragrant, about 1 minute.

4. Add onion and salt, and cook, stirring often, until onion begins to soften, about 2 minutes.

5. Add brown sugar, soy sauce, ketchup, and rice vinegar; bring to a simmer, stirring constantly, until sugar is dissolved.

6. Sprinkle pineapple and bell pepper evenly in bottom of a lightly greased 3 quart baking dish.

7. Pour brown sugar-soy mixture over pineapple mixture; top evenly with chicken tenders.

8. Bake in preheated oven until bubbly, and chicken is slightly crisp on top, about 20 minutes.

9. Toss mixture lightly to coat chicken, and sprinkle with scallions.

10. Serve over rice.
* Instant Pot Chicken Taco Bowls
** Link:
- https://wondermomwannabe.com/instant-pot-chicken-taco-bowls/
** Ingredients
- 4 to 5 uncooked boneless, skinless breasts if large, cut in half
- 1 to 2 packets taco seasoning 1 for mild flavor, 2 for more flavor
- 1 15 oz can black beans, drained and rinsed
- 1 12 oz bag frozen corn
- 1 15.5 oz jar salsa
- 3 cups uncooked jasmine rice rinsed
- 3 cups water or chicken broth
- cheddar cheese
- cilantro optional
- sour cream optional
** Directions
1. Add one cup of liquid (water or broth) to the bottom of the pot.
2. Place chicken breasts in bottom of pressure cooker on top of the liquid.
3. Sprinkle with taco seasoning.
4. Top with beans and corn.
5. Then, pour salsa over everything.
6. Add rice, then remaining liquid (water or broth).
7. Cook on manual high pressure for 12 minutes.
8. Then, use quick release to release the pressure.
9. Once the pressure has been fully released, remove lid carefully.
10. Shred chicken.
11. Serve immediately.
12. Top with cheddar cheese, cilantro, and sour cream as desired.
* Instant Pot Mac And Cheese Recipe
** Links:
- https://www.myrecipes.com/recipe/instant-pot-mac-and-cheese-with-bacon
- https://www.youtube.com/watch?v=kOAXRpKHdTY&t=1295s
** Ingredients:
- 4 strips bacon, chopped
- 1 pound uncooked medium pasta shells
- 4 cups water
- 2 tablespoons unsalted butter
- 2 teaspoons salt
- 1 (5-ounce) can evaporated milk
- 8 ounces cheddar cheese, shredded
- 8 ounces Gouda, shredded
- black pepper to taste
** Directions:
1. In a 6-quart Instant Pot® add chopped bacon and press [Sauté].

2. Cook bacon for 8 minutes or until crispy.

3. Remove bacon with a slotted spoon and set aside.

4. Turn Instant Pot off by hitting [Cancel].

5. Add the pasta, water, butter, and salt.

6. Close and lock the lid of the Instant Pot® and press [Manual], select high pressure and use [Adjust] to select "Less" mode.

7. Press [-] or [+] to choose 4 minutes cook time.

8. Carefully turn knob to vent position to release steam.

9. Remove lid.

10. Stir in the evaporated milk, cheddar cheese, Gouda cheese and black pepper.

11. Press [Sauté] and cook for about 4 minutes or until the cheese had melted, stirring frequently.

12. Stir in bacon and serve warm.
* Italian Style Green Bean Casserole Recipe
** Links:
- https://www.myrecipes.com/recipe/Italian-style-green-bean-casserole
- https://www.youtube.com/watch?v=_wZkmBUkdbE
** Ingredients:
- 6 ounces Parmesan cheese, grated (about 1 1/2 cups), divided
- 1 1/4 cups Italian-style breadcrumbs, divided
- 4 garlic cloves, minced
- 1 teaspoon kosher salt
- 3/4 teaspoon black pepper, divided
- 3 (28-oz.) cans Italian-style green beans, drained
- 2 (9-oz.) pkg. frozen artichoke hearts, thawed, drained well and chopped
- 2/3 extra-virgin olive oil
- Fresh flat-leaf parsley, chopped
** Directions:
1. Preheat oven to 375°F.

2. Combine Parmesan, breadcrumbs, garlic, salt, and 1/2 teaspoon pepper in a large bowl.

3. Reserve 1/3 cup of the breadcrumb mixture; set aside.

4. Add green beans, artichoke hearts, and olive oil to bowl with remaining breadcrumb mixture, and fold to combine well.

5. Pour green bean mixture into a lightly greased 13- x 9-inch baking dish.

6. Sprinkle reserved breadcrumb mixture evenly over casserole.

7. Cover with aluminum foil, and bake until heated through, about 30 minutes.

8. Uncover and bake until lightly golden and bubbly, about 10 minutes.

9. Sprinkle with remaining 1/4 teaspoon pepper, and if desired, chopped parsley.
* Kale Pie Recipe
** Link:
- https://ingmar.app/blog/kale-pie-with-walnuts-and-blue-cheese/
* Langos Recipe
** Link:
- https://honestcooking.com/hungarian-langos/
** Ingredients:
- 300 g all-purpose flour (1.27 cups)
- 7 g dried (instant) yeast (1.40 teaspoons)
- 250 ml water (1.05 cups)
- 1/2 teaspoon salt
- sunflower oil for frying
- toppings: sour cream, grated cheese, garlic
** Directions:
1. In a mug dissolve the salt in the water.

2. In a bowl combine the sifted flour with the yeast.

3. Add salty water to it and stir through (if it’s very sticky, add a little bit more flour).

4. Work the dough with a wooden spoon or with your hands until the dough comes off the bowl and gets smooth.

5. Leave the dough in the bowl, cover with a clean cloth and let it rise for 30-40 minutes or until it has doubled in bulk.

6. Once it is rested, carefully tip out the dough onto a floured surface, stretch out into a square and cut out about 10 cm (3,93 inch) round shapes with a big glass (big cookie cutter also good).

7. Stretch out each piece with your fingers into a round shape with the centre being thinner than the edges.

8. Let the pieces rest for another 30 minutes on the floured surface.

9. In a saucepan heat sunflower oil.

10. Place lángos into the hot oil, fry it on one side until golden brown then turn.

11. Repeat with the remaining lángos dough.

12. Serve while it’s hot.

13. You can eat it simple or sprinkle with chopped garlic or douse with garlic water and top with grated cheese and sour cream.
* Overnight Oats Recipe
** Link:
- https://lemonsandzest.com/stumbling-blocks-stepping-stones-recipe-peanut-butter-cup-overnight-oats/
** Ingredients:
- 1/2 cup rolled oats regular or gluten free
- 2 to 3 tsp peanut butter or any nut or seed butter
- 1 tsp cocoa powder
- 1 tsp vanilla
- 2 tsp pure maple syrup or honey
- 1/2 cup milk of choice
- Dash of sea salt
- 1 tsp chia seeds optional
** Directions:
1. Combine all ingredients in small jar or bowl that can be sealed.

2. Stir well and then cover.

3. Refrigerate overnight.

4. Serving options: serve with a sprinkle of cocoa nibs, extra peanut butter drizzle, dark chocolate chips, or sliced banana.
* Meatball Stroganoff Recipe (One-Pot)
** Link:
- https://www.pillsbury.com/recipes/one-pot-meatball-stroganoff-for-two/3a2b6bb9-fb65-4f09-8ba5-211ef587d272
** Ingredients:
- 2 tablespoons butter
- 4 oz sliced baby bella mushrooms (about 1 1/3 cups)
- 1/8 teaspoon salt
- 1/8 teaspoon pepper
- 2 cups Progresso™ beef flavored broth (from 32-oz carton)
- 2 cups uncooked wide egg noodles (from 12-oz bag)
- 12 frozen fully cooked beef meatballs, thawed (from 22-oz bag)
- 1/3 cup sour cream
** Directions:
1. In 2-quart saucepan, heat butter over medium-high heat.

2. Add mushrooms, salt and pepper; cook 3 to 5 minutes, stirring frequently, until tender.

2. Add beef broth, egg noodles and meatballs; heat to boiling.

3. Reduce heat to medium; simmer uncovered 9 to 11 minutes, stirring occasionally, until liquid is mostly absorbed.

4. Remove from heat; let stand 5 minutes.

5. Stir in sour cream; serve immediately.
* Nokedli Recipe
** Link:
- https://dailynewshungary.com/traditional-hungarian-nokedli-dumpling-recipe-as-we-inherited-it-from-our-grandmothers/
** Ingredients (converted from metric to imperial units)
- 2 cups flour
- 4 eggs
- 0.84535057 cup water (less than a cup, 200 mL water originally)
- pinch of salt
** Directions:
1. Mixing the dough: After the ingredients are prepared, you can start mixing the dough.

2. First, pour the flour, the eggs and the salt into a bowl.

3. If you do not add enough eggs, the dough will be too sticky.

3. Start combining the first two ingredients and add water gradually.

4. The secret of good dumplings is that you should not overmix the dough or leave it to rest because it can harden.

5. Put a bigger pot of water to boil (add some salt and oil to the water) before you start mixing the ingredients.

6. Forming the dumplings: You can use a dumpling maker/grater, a teaspoon or a knife to form the dumplings.

7. In the first case, place the grater on top of the pot, fill the sliding basket with the dough and slide it back and forth.

8. I would recommend using a spoon because it allows you to form even and perfectly-shaped ‘nokedli’.

9. Stir the dumplings occasionally, so they do not stick to the bottom of the pot.

10. Cooking the dumplings: You have to keep it in mind that dumplings do not take much time to cook, so try forming them as quickly as you can.

11. The dumplings are ready when they float to the surface of the water.

12. Rinsing and seasoning: After you drain the cooked dumplings, you can rinse them with water so they do not stick together.

13. However, this step is a bit controversial since it cools the dish.

14. Another solution is to add a bit of oil, fat or butter to the dumplings.

15. You can season the dumplings with some chives or garlic and it is the perfect side dish for chicken paprikash.
* Philly Mac And Cheese Steak Casserole Recipe
** Links:
- https://www.myrecipes.com/recipe/philly-mac-and-cheese-steak
- https://www.youtube.com/watch?v=_wZkmBUkdbE
** Ingredients:
- 4 teaspoons olive oil, divided
- 1 cup sliced mushrooms
- 1 cup thinly sliced onion (from 1 onion)
- 3/4 cup sliced red bell pepper (from 1 pepper)
- 3/4 cup sliced green bell pepper (from 1 pepper)
- 1 teaspoon garlic powder
- 3/4 teaspoon kosher salt
- 1/2 teaspoon black pepper
- 4 tablespoons unsalted butter
- 4 tablespoons all-purpose flour
- 2 1/2 cups whole milk
- 2 teaspoons Worcestershire sauce
- 1/2 teaspoon dry mustard
- 4 ounces processed cheese (such as Velveeta)
- 8 ounces cavatappi or elbow pasta, prepared according to package directions
- 12 ounces chopped deli roast beef
- 8 ounces sharp provolone cheese, shredded (about 2 cups), divided
- 1/3 cup panko (Japanese-style bread crumbs)
- Chopped fresh flat-leaf parsley (optional)
** Directions:
1. Preheat oven to 375°F.

2. Heat 1 tablespoon of the oil in a large skillet over medium-high.

3. Add mushrooms, onion, and bell peppers; cook, stirring constantly, until veggies begin to soften, about 3 minutes.

4. Add garlic powder, salt, and pepper; cook, stirring often, 2 minutes.

5. Add butter to veggie mixture; cook until butter is melted.

6. Sprinkle in flour; cook, stirring constantly, 1 to 2 minutes.

7. Whisk in milk, Worcestershire, and dry mustard until smooth.

8. Reduce heat to medium-low, and stir in Velveeta until smooth.

9. Remove from heat, and stir in cooked pasta, roast beef, and 1 1/4 cups provolone until combined.

10. Pour mixture into an 11- x 7-inch baking dish lightly coated with cooking spray; top with remaining 3/4 cup cheese.

11. Stir together panko and remaining 1 teaspoon oil in a small bowl.

12. Sprinkle breadcrumb mixture evenly over pasta mixture, and bake in preheated oven until golden and bubbly, 20 to 25 minutes.

13. Sprinkle with parsley, if desired.
* Pho Recipe
** Link:
- https://www.vice.com/en_us/article/yw75w7/homemade-pho-recipe?
** Ingredients:
*** Broth
- 7 pounds beef bones with marrow (can do oxtail)
- 1 pound beef brisket
- 3 pounds chuck short rib
- 1/4 cup fish sauce
- 6-8 shallots
- 2 large hands ginger
- 2 large white onions, halved
- 1 tablespoon coriander seed
- 1 tablespoon fennel seed
- 10 whole fructus amomi
- 5 whole star anise
- 6 whole cloves
- 3 cinnamon sticks
- 1 whole green cardamom pod
*** For Serving
- 1 pound, 450 grams pho rice noodles
- 1/2 pound eye of round, sirloin, flank, London broil, sliced very thinly
- 1 bunch scallions, sliced into small rings
- 1 medium onion, sliced thinly
- 3-4 cups bean sprouts
- 1 bunch cilantro
- 1 bunch Thai basil
- Lime wedges
- hoisin sauce
- Sriracha sauce
** Directions:
1. Place the beef bones into a stockpot of 10 to 12-quart capacity.

2. Fill the pot with enough water to just cover all the bones, leaving at least 1 inch at the top to allow room for boiling.

3. Heat the pot on high until the water boils and let it continue to boil aggressively for 5 minutes to release impurities from the sides of the bones.

4. Once clean, turn off the heat. Pour the contents of the pot into a colander or directly into a clean sink that is lined with a strainer to catch solids.

5. Rinse the bones until they are clean of blood and impurities. Be careful not to lose any marrow in the process.

6. Char the onion, ginger, and shallots either by holding them with metal tongs over an open flame or setting them directly on an electric burner.

7. Alternatively, you can put them under a broiler.

8. Remove once they take on some color and char, but before they become burned.

9. Make sure the onion and shallots are at the very top of the stockpot during the simmering time so that you can remove them if they begin to disintegrate into the stock.

10. In a small dry pan, toast the spices on low heat for a few minutes, or until they begin to release their aroma.

11. Add the toasted spices into the fine mesh bag or cheesecloth and tie shut with string.

12. Put the parboiled and/or roasted bones into a clean stockpot.

13. Add the chuck for flavor, brisket, oxtail, or short ribs you plan to serve.

14. Add the charred onion, ginger, shallots, and toasted spices.

15. Fill the pot with water, or until all the ingredients are covered.

16. Turn the heat on high, but keep a close eye on the pot to prevent the water from reaching a full boil.

17. Just before the water reaches boiling (small bubbles will begin to rise), turn the heat to the lowest setting to maintain a very low simmer.

18. If you’re not already using the smallest burner on your stovetop, then move the pot there now to keep the heat at a minimum.

19. You want as little movement in the water as possible.

20. Keep the broth at a very low simmer for 6 to 8 hours, skimming regularly for any scum and impurities that rise to the surface.

21. If you are not using a mesh bag or cheesecloth to hold the onion and garlic, check to make sure that they don’t start to disintegrate and cloud the stock after several hours if so, go ahead and remove them.

22. For the eye of round, which will be served rare, put the whole raw piece of meat in the freezer for about 30 minutes to let it harden a bit. This makes it easier to slice thinly.

23. Then take the meat out and slice across the grain as thinly as possible.

24. Refrigerate the sliced meat until the pho is ready to serve.

25. If cooking flank, brisket, or oxtail, check the softness of these meats after 2 to 3 hours of simmering in the stock (depending on how large the pieces of oxtail, that cut may take longer).

26. When tender, take these meats out (but make sure to leave the chuck in) and let them rest for at least 15 minutes.

27. Slice the flank and brisket across the grain. Leave small pieces of oxtail as is or, if large, they can also be roughly shredded with a fork.

28. Let the meat cool, then refrigerate until ready to serve.

29. After the stock has simmered 6-8 hours, remove all of the stock ingredients (bones, meat, aromatics, and spices).

30. Strain the broth with a cheesecloth to filter out everything.

31. Season the broth with the rock sugar and fish sauce, starting in small increments and tasting as you go.

32. The broth should end up on the saltier side and will balance out when served with the noodles and other ingredients.

33. I usually end up with about 4 quarts of broth after simmering and find that the listed amount of salt and fish sauce is about what’s needed for my tastes.

34. But every pot of broth turns out differently depending on many factors, and you may end up with more or less liquid after simmering, so season incrementally and according to your tastes.

35. You can also add more sugar if you like your pho on the sweeter side.

36. After seasoning, the broth can be either served right away or allowed to cool at room temperature.

37. If serving right away, the fat can be skimmed off with a spoon (though a little bit of fat lends flavor!).

38. Always cook the noodles in a separate pot of water, never in the stock itself.

39. If cooking the noodles beforehand (that is, before your broth is ready), always undercook them slightly since they will need to be reheated before serving.

40. If using dried noodles, first soak them in hot water for 30 minutes.

41. Then, add the soaked noodles to a pot of boiling water and cook for about 20 seconds.

42. Drain and rinse under cold water.

43. If using fresh noodles, loosen them first under cold water before adding them into a pot of boiling water.

44. Cook for about 20 seconds or until just al dente.

45. Drain and rinse under cold water.

46. To reheat just before serving, place individual portions of noodles in a sieve and submerge the sieve into boiling water for a few seconds, just until the noodles come loose.

47. Serve with all the fixings for people to build their own bowls.
* Pogacsa Recipe
** Link:
- https://www.food.com/recipe/pogacsa-hungarian-cheese-biscuits-510722
** Ingredients:
- 1/2 cup whole milk, heated to 110 degrees F to 115 degrees F
- 2 teaspoons active dry yeast
- 1/2 teaspoon sugar
- 4 cups all-purpose flour
- 5 ounces gruyere cheese, finely shredded
- 1 tablespoon salt
- 2 eggs
- 14 tablespoons unsalted butter, softened (1 3/4 American sticks)
- 1/2 cup sour cream
** Topping Ingredients:
- 1 egg yolk
- 2 ounces gruyere cheese, finely shredded
** Directions:
1. In a large bowl, combine milk, yeast and sugar and let stand until yeast is softened, about 10 minutes.

2. Add flour, cheese, salt, eggs, butter, and sour cream to the yeast mixture.

3. Using an electric mixer, mix on low speed until dough comes together.

4. Beat on medium speed 1 to 2 minutes. The dough should be smooth and not sticky.

5. Roll dough 1/2 inch thick on a lightly floured surface.

6. Make a shallow cross-hatched pattern with the point of a sharp knife over the top of the dough and brush with egg yolk.

7. Sprinkle cheese on top, and cut out rounds with a 1 to 1 1/2 inch cutter.

8. Arrange circles in rows on a parchment-lined baking sheet, about 1/4 inch apart.

9. Put pan in a cold oven and set temperature to 400 degrees F.

10. Bake about 25 minutes, until pogacsa are nicely browned on their tops and bottoms.

11. Let cool completely and store airtight.

12. Pogacsa may also be frozen up to 1 month.

13. Thaw and reheat at 225 degrees F for 20 minutes.
* Porkolt Recipe
** Link:
- https://www.allrecipes.com/recipe/190100/porkolt-hungarian-stew-made-with-pork/
** Ingredients:
- 5 slices bacon, diced
- 2 large onions, diced
- 1/4 cup Hungarian paprika
- 1 1/2 teaspoons garlic powder
- 1/4 teaspoon ground black pepper
- 5 pounds boneless pork chops, trimmed
- 1 large yellow bell pepper, seeded and diced
- 2 (14 ounce) cans diced tomatoes, with liquid
- 2/3 cup beef broth
- 2 cups reduced-fat sour cream
- 2 (6 ounce) packages wide egg noodles
** Directions:
1. Place the bacon in a large, deep skillet, and cook over medium-high heat until evenly browned, about 10 minutes.

2. Drain, and reserve the drippings.

3. Add the onions to the bacon and cook together until the onion is translucent.

4. Remove skillet from heat and stir the paprika, garlic powder, and pepper into the bacon mixture.

5. Transfer the mixture into a large stockpot.

6. Heat a small amount of the reserved bacon drippings in the skillet again over medium-high heat.

7. Cook the pork chops in batches in the hot drippings until evenly browned on both sides.

8. Use additional bacon drippings for each batch as needed.

9. Remove the pork chops to a cutting board and blot excess fat off the surface of the chops with a paper towel.

10. Cut into bite-sized cubes and stir into the bacon mixture.

11. Heat a small amount of the bacon drippings in the skillet.

12. Cook and stir the bell pepper in the hot drippings until softened and fragrant.

13. Drain on a plate lined with paper towels.

14. Stir the cooked pepper into the bacon mixture.

15. Pour the tomatoes with liquid and beef broth into a stockpot and place the pot over medium-high heat.

16. Bring to a simmer and reduce heat to medium-low.

17. Cook until the stew begins to thicken, stirring occasionally, about 90 minutes.

18. Stir the sour cream into the stew just before serving.

19. Bring a pot with lightly-salted water and bring to a rolling boil.

20. Add the egg noodles to the water and return to a boil.

21. Cook uncovered, stirring occasionally, until the pasta has cooked through, but is still firm to the bite, about 5 minutes.

22. Drain well in a colander set in the sink.

23. Ladle the stew over the drained noodles to serve.

* Rakott Krumpli (Hungarian Layered Potatoes) Recipe
** Link:
- https://www.youtube.com/watch?v=S_vlBM95g1A&t=175s
** Ingredients (Serves 6):
- 4 lbs (about 2kg) potatoes (use waxy or all-purpose type, which retain their shape)
- 8 eggs
- 3 oz (80-100g gr) smoked bacon
- 1 lb (450gr) Smoked Hungarian Sausage (or Chorizo)
- 1.1 lbs (500 gr) full fat sour cream
- 1 tsp Paprika
- 1 tbsp Vegeta (all purpose seasoning) – optional
- Salt
** Directions:
1. In a large pot boil the potatoes with skin on until almost done.

2. Be careful, do not overcook! It's better if slightly under-cooked (as they will cook in the oven too).

3. Make 8 hard boiled eggs.

4. Cut the smoked bacon into small cubes, then cook them until golden (half-done).

5. Cut the sausage (not too thin) slices.

6. When the potatoes are ready, drain them and let them cool a little.

7. Peel and slice the eggs.

8. Peel the boiled potatoes while they're still warm (almost hot, if you can handle them).

9. Not too thinly slice all the potatoes, or, you can slice them directly into the tray when layering the dish.

10. Mix the sour cream with 1 tbsp of Vegeta (all-purpose seasoning). It's optional, you can use the sour cream without it. (I like it, because it gives a nice, salty flavor).

11. Preheat the oven to 350F (180 C).

12. Grease the baking tray with the fat from the bacon.

13. Place one layer of the sliced potatoes, then sprinkle with salt. The second layer is the sliced sausage, then one layer of sliced eggs.

14. Cover it with the (seasoned) sour cream.

15. Repeat this one more time: potatoes, (salt), sausages, eggs, sour cream.

16. Finish it with a layer of potatoes, covered with sour cream.

17. Sprinkle the bacon pieces on top (you can add some bacon pieces between the layers too!), and also sprinkle some paprika on top.

18. Bake in the preheated oven for 40-45 minutes (until the top is nicely browned, the sausages released their fat, and the sour cream is set).

19. Let it stay and cool about 10-15 minutes, then serve.

20. You can add some extra sour cream on top, and serve some pickles on side.
* Sausage Gravy Breakfast Pizza
** Link:
- https://flavorite.net/sausage-gravy-breakfast-pizza/
** Ingredients:
** Directions:
* Smoked Salmons And Chive Soda Bread
** Link:
- https://thegreatbritishbakeoff.co.uk/recipes/all/hermine-smoked-salmon-and-chive-soda-bread/
** Ingredients:
*** For the bread:
- 200g plain flour
- 2 tbsp plain wholemeal flour
- 2 tbsp spelt flour
- 1/2 tsp baking powder
- 1 tsp bicarbonate of soda
- 1/2 tsp cream of tartar
- 2 tbsp porridge oats
- 3 tsp onion powder
- 30g salted butter, chilled
- 120g smoked salmon, very finely chopped
- 50g gruyère cheese, grated
- 15g chives, finely snipped
- Good pinch of freshly ground black pepper
- 1 large egg
- 160ml buttermilk
- 1 tbsp runny honey
*** For the dill and black garlic butter:
- 300ml double cream
- 1 whole bulb of black garlic, flesh squeezed out
- 30g dill fronds, finely chopped
- pinch of sea salt
- 1 lemon wedge and dill sprig, to decorate
** Directions:
1. Heat the oven to 220°C/200°C fan/Gas 7.

2. Sift the flours, baking powder, bicarbonate and cream of tartar together into a mixing bowl.

3. Stir in the porridge oats and onion powder.

4. Add the butter, rubbing it into the flour until it’s finely distributed.

5. Stir in the salmon, cheese, chives and pepper and toss everything together.

6. Crack the egg into a measuring jug and add enough buttermilk to give 210ml.

7. Add the honey and beat the mixture together with a fork.

8. Stir the wet ingredients into the dry using a round-bladed knife until they come together, then gather the mixture into a ball.

9. Turn out the dough onto a floured work surface, flatten the ball slightly, then place it on a baking sheet.

10. Using a sharp knife, cut a deep cross in the top.

11. Bake for 35–40 minutes, or until golden brown and a skewer inserted into the centre comes out clean.

12. While the bread is baking, make the butter.

13. Place the cream in the bowl of a stand mixer fitted with the whisk attachment.

14. Whisk on a medium speed until the cream curdles, the butter solidifies on the whisk, and the buttermilk separates from the fat.

15. Place the butter inside the muslin-lined sieve over a bowl.

16. Gather up the muslin and squeeze gently to remove the excess buttermilk, then place the butter in a separate bowl.

17. Add the squeezed garlic into the bowl with the butter, along with the chopped dill and pinch of sea salt.

18. Use a hand-held stick blender to blitz until smooth, then spoon into a serving bowl.

19. Garnish with lemon and dill and serve alongside the bread.
* Stuffed Peppers Recipe
** Link:
- https://www.youtube.com/watch?v=_yRH88ooGtg
** Ingredients:
- 7-8 yellow wax pepper
- 1 lb ground pork
- About 1 cup rice
- 1 onion / finely chopped
- 1 egg
- 2 garlic cloves / crushed
- 1 jar (750ml --> 25 oz) thick tomato juice (use Passata if you can find it)
- 3 to 4 tsp tomato paste
- 2 tbsp sugar
- 3 tbsp flour
- 6 tbsp oil
- 4 potatoes (cut into wedges)
- 1 bunch celery leaves (optional)
- Salt, pepper, paprika
** Directions:
1. Heat 2 tbsp oil in a saucepan, add the chopped onion and cook gently until it's soft.

2. Remove from the heat.

3. Cut the stem of the peppers off and deseed them.

4. Place the ground pork in a large bowl, then season with 2 tsp salt, 1 tsp black pepper and 1 heaped tsp paprika.

5. Add the crushed garlic, 1 egg, the pre-washed rice and the softened onion.

6. Using your hands mix everything together, until it's well combined.

7. Fill the peppers with the meat mixture (do not over-stuff them as the rice will expand).

8. If you have meat-mixture left, make some meatballs from it.

9. Heat 4 tbsp oil in a large saucepan, add the flour and cook stirring until it's golden brown.

10. Gently pour the thick tomato juice into the pan, add a little water and mix well.

11. Add 3-4 heaped tsp tomato paste, and season with salt, sugar and black pepper (and also add the celery leaves if you haves some – it's optional).

12. Mix together /it should look like a nice creamy soup.

13. Add the stuffed pepper and meatballs, cover, and cook on low heat at least 1 hour.

14. Check it sometimes, gently stir and turn the peppers over.

15. After 1 hour of cooking the peppers should be soft and the meat cooked through.

16. Meanwhile cook the potato wedges in boiling salted water.

17. When the potato wedges are cooked, drain them in a colander.

17. Now, serve the stuffed peppers and meatballs with the tomato sauce and the boiled potatoes on side.
* Toltott Kaposzta (Hungarian Stuffed Cabbage)
** Link:
- https://www.tasteofhome.com/recipes/hungarian-stuffed-cabbage/
** Ingredients:
- 1 medium head cabbage
- 1 can (28 ounces) sauerkraut, divided
- 1/2 pound ground beef
- 1/2 pound ground pork
- 1/2 cup long grain rice, cooked
- 1 teaspoon salt
- 1/2 teaspoon pepper
- 1 large egg
- 2 bacon strips, diced
- 1 cup chopped onion
- 2 garlic cloves, minced
- 1 tablespoon Hungarian paprika
- 1/4 teaspoon cayenne pepper
- 1 can (14-1/2 ounces) diced tomatoes, undrained
- 1 tablespoon caraway seeds
- 2 cups water
- 2 tablespoons all-purpose flour
- 1 cup sour cream
** Directions:
1. Remove core from head of cabbage.

2. Place in a large saucepan and cover with water.

3. Bring to a boil

4. Boil until outer leaves loosen from head.

5. Lift out cabbage and remove softened leaves.

6. Return to boiling water to soften more leaves.

7. Repeat until all leaves are removed.

8. Remove tough center stalk from each leaf.

9. Set aside 12 large leaves for rolls

10. Set remaining leaves aside.

11. Spoon half of the sauerkraut into a Dutch oven and set aside.

12. In a bowl, combine the beef, pork, rice, salt, pepper and egg.

13. In a saucepan, cook bacon until crisp.

14. Drain on paper towels.

15. In drippings, saute onion and garlic until tender.

16. Add bacon and half of onion mixture to meat mixture and mix well.

17. Preheat oven to 325°.

18. Place about 3 tablespoons filling on each cabbage leaf.

19. Roll up, tucking in sides.

20. Place rolls, seam side down, on sauerkraut in Dutch oven.

21. Coarsely chop reserved cabbage leaves and place over rolls.

22. Add paprika, cayenne, tomatoes, caraway seeds, water and remaining sauerkraut to remaining onion mixture.

23. Cook until heated through, and pour over rolls.

24. Cover and bake for 1 hour 45 minutes.

25. In a small bowl, gradually stir flour into sour cream.

26. Stir in 1 to 2 tablespoons hot cooking liquid and mix well, and spoon over cabbage rolls.

27. Bake, uncovered, until sauce is thickened, 15-20 minutes.
* Taco Cake Recipe
** Link:
- https://ingmar.app/blog/taco-cake/
* Tiger Bread Recipe
** YouTube Video Link:
- https://www.youtube.com/watch?v=zjMznWyYkpM
** Ingredients:
*** For The Dough
- 500g Strong white bread flour
- 1 Easy bake yeast sachet ((7g))
- 1.5 tsp Unrefined golden caster sugar
- 1.5 tsp Salt
- 1 tbsp Butter (softened )
- 300ml Warm water
*** For the topping
- 3.5g Easy bake yeast
- 0.5 tbsp Unrefined golden caster sugar
- 0.5 tbsp Vegetable oil
- 1 pinch Salt
- 75g Ground rice
- 6 tbsp Warm water
** Directions:
1. MIX: Mix the flour, yeast, sugar and salt in a big bowl.

2. Using your fingertips rub in the butter until only fine ‘crumbs’ are left.

3. Mix in the water with a cutlery knife.

2. KNEAD: Tip onto a lightly flour dusted surface and knead for 10 minutes (or use the dough hook attachment on your mixer).

3. RISE: Lightly grease the mixing bowl with some oil.

4. Put the dough back in, cover the bowl with a clean tea towel and leave to rise until doubled in size.

5. SHAPE: Knock back the dough by gently kneading just 5 times to get the air out.

6. Shape into a smooth oval and sit on a floured baking sheet.

7. PROVE: Cover the dough again with a clean tea towel and leave to prove until doubled in size again.

8. Preheat your oven to 200°C (fan 180°C, gas mark 6).

9. WHISK: Whisk all of the topping ingredients together until smooth.

10. Leave this to rest for 10 minutes.

11. BAKE: Spread the paste all over the top and sides of your loaf – use a palette knife or your hands.

12. Bake for 35 minutes, until it’s golden brown and crackled and when you tap the base it sounds hollow.

13. Cool on a wire rack.
* Turkey Meatloaf Recipe
** Link:
- https://www.allrecipes.com/recipe/231380/best-turkey-meatloaf/
** Ingredients:
*** Meatloaf Ingredients:
- 1  1/2 pounds ground turkey
- 3/4 cup crushed buttery round crackers
- 1/2 cup milk
- 1 small onion, chopped
- 1 egg
- 1  1/2 teaspoons salt
- 2 cloves garlic, minced
- 1/4 teaspoon ground black pepper
*** Topping Ingredients:
- 1/2 cup ketchup
- 1/4 cup brown sugar
- 1 tablespoon Worcestershire sauce
** Directions:
1. Preheat oven to 350 degrees F (175 degrees C).

2. Lightly grease a jelly roll pan.

3. Mix ground turkey, buttery round cracker crumbs, milk, onion, egg, salt, garlic, and black pepper in a bowl

4. Shape into a loaf and place on the prepared jelly roll pan.

5. Mix ketchup, brown sugar, and Worcestershire sauce in a separate bowl and set aside.

6. Bake meatloaf in preheated oven for 30 minutes

7. Remove meatloaf from oven and drain liquids.

8. Top meatloaf with ketchup topping.

9. Return loaf to oven and continue baking until no longer pink in the center, about 30 minutes more.

10. An instant-read thermometer inserted into the center should read at least 160 degrees F (70 degrees C).
* Zöldbab Krémmel Greenbeans With Cream Recipe
** Link:
- https://www.matildaiscooking.com/recipes/date/2018-04
** Ingredients:
- 1 kg Greenbeans
- 1 Tablespoon of salt
- 2 Tablespoons of Oil
- 1 Tablespoon of butter
- 2 Tablespoons of Flour
- 250ml Fresh Cream
- 1 Tablespoon of Vinegar
** Directions:
1. Watch this video: https://www.youtube.com/watch?v=RrlZqF47W8c&feature=emb_logo

2. Watch Matilda for Directions: Total Cooking Time Approx 35-40 Minutes.

3. Ensure the beans are cooked before mixing together.
